[features]
seeds = false
[programs.localnet]
anchor_test = "HKu3iNjUuQbimNN4W6qZahvXn4rchaESwcPvsV1sdQsW"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/duyanh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
